#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean time directories only

foamListTimes -rm
rm -f log.* 2>/dev/null
# rm -r postProcessing

#------------------------------------------------------------------------------